// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/Killazius/L0/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderProvider creates a new instance of MockOrderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderProvider {
	mock := &MockOrderProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderProvider is an autogenerated mock type for the OrderProvider type
type MockOrderProvider struct {
	mock.Mock
}

type MockOrderProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderProvider) EXPECT() *MockOrderProvider_Expecter {
	return &MockOrderProvider_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockOrderProvider
func (_mock *MockOrderProvider) GetAll(ctx context.Context) ([]domain.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderProvider_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockOrderProvider_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderProvider_Expecter) GetAll(ctx interface{}) *MockOrderProvider_GetAll_Call {
	return &MockOrderProvider_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockOrderProvider_GetAll_Call) Run(run func(ctx context.Context)) *MockOrderProvider_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderProvider_GetAll_Call) Return(orders []domain.Order, err error) *MockOrderProvider_GetAll_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderProvider_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Order, error)) *MockOrderProvider_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderSetter creates a new instance of MockOrderSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderSetter {
	mock := &MockOrderSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderSetter is an autogenerated mock type for the OrderSetter type
type MockOrderSetter struct {
	mock.Mock
}

type MockOrderSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderSetter) EXPECT() *MockOrderSetter_Expecter {
	return &MockOrderSetter_Expecter{mock: &_m.Mock}
}

// Set provides a mock function for the type MockOrderSetter
func (_mock *MockOrderSetter) Set(ctx context.Context, order *domain.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderSetter_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockOrderSetter_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - order *domain.Order
func (_e *MockOrderSetter_Expecter) Set(ctx interface{}, order interface{}) *MockOrderSetter_Set_Call {
	return &MockOrderSetter_Set_Call{Call: _e.mock.On("Set", ctx, order)}
}

func (_c *MockOrderSetter_Set_Call) Run(run func(ctx context.Context, order *domain.Order)) *MockOrderSetter_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Order
		if args[1] != nil {
			arg1 = args[1].(*domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSetter_Set_Call) Return(err error) *MockOrderSetter_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderSetter_Set_Call) RunAndReturn(run func(ctx context.Context, order *domain.Order) error) *MockOrderSetter_Set_Call {
	_c.Call.Return(run)
	return _c
}
