http_server:
  port: "8081"
  host: "0.0.0.0"
  timeout: 5s
  idle_timeout: 60s
logger:
  path: "config/logger.json"
postgres:
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 1h
  conn_max_idle_time: 25m
  timeout: 5s
kafka:
  brokers:
    - "kafka:9092"
  topic: "orders"
  group_id: "order-service-group"
  auto_offset_reset: "earliest"
  session_timeout: 30s
  max_wait: 10s
  min_bytes: 10240
  max_bytes: 10485760
  max_retries: 3
  enable_auto_commit: false
  commit_interval: 1s
