http_server:
  port: "8080"
  host: "0.0.0.0"
  timeout: 5s
  idle_timeout: 60s
logger:
  path: "config/logger.json"
postgres:
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 1h
  conn_max_idle_time: 25m
  timeout: 5s
