// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/order/{order_uid}": {
            "get": {
                "description": "Get order details by order UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get order by UID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order UID",
                        "name": "order_uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order details",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    },
                    "400": {
                        "description": "Invalid order UID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Delivery": {
            "type": "object",
            "required": [
                "address",
                "city",
                "email",
                "name",
                "phone",
                "region",
                "zip"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Ploshad Mira 15"
                },
                "city": {
                    "type": "string",
                    "example": "Kiryat Mozkin"
                },
                "email": {
                    "type": "string",
                    "example": "test@gmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "Test Testov"
                },
                "phone": {
                    "type": "string",
                    "example": "+9720000000"
                },
                "region": {
                    "type": "string",
                    "example": "Kraiot"
                },
                "zip": {
                    "type": "string",
                    "example": "2639809"
                }
            }
        },
        "domain.Item": {
            "type": "object",
            "required": [
                "brand",
                "chrt_id",
                "name",
                "nm_id",
                "price",
                "rid",
                "size",
                "status",
                "total_price",
                "track_number"
            ],
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "Vivienne Sabo"
                },
                "chrt_id": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 9934930
                },
                "name": {
                    "type": "string",
                    "example": "Mascaras"
                },
                "nm_id": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 2389212
                },
                "price": {
                    "type": "number",
                    "example": 453
                },
                "rid": {
                    "type": "string",
                    "example": "ab4219087a764ae0btest"
                },
                "sale": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 30
                },
                "size": {
                    "type": "string",
                    "example": "0"
                },
                "status": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 202
                },
                "total_price": {
                    "type": "number",
                    "example": 317
                },
                "track_number": {
                    "type": "string",
                    "example": "WBILMTESTTRACK"
                }
            }
        },
        "domain.Order": {
            "description": "Order information",
            "type": "object",
            "required": [
                "customer_id",
                "date_created",
                "delivery",
                "delivery_service",
                "entry",
                "items",
                "locale",
                "oof_shard",
                "order_uid",
                "payment",
                "shardkey",
                "sm_id",
                "track_number"
            ],
            "properties": {
                "customer_id": {
                    "type": "string",
                    "example": "test"
                },
                "date_created": {
                    "type": "string",
                    "example": "2021-11-26T06:22:19Z"
                },
                "delivery": {
                    "$ref": "#/definitions/domain.Delivery"
                },
                "delivery_service": {
                    "type": "string",
                    "example": "meest"
                },
                "entry": {
                    "type": "string",
                    "example": "WBIL"
                },
                "internal_signature": {
                    "type": "string",
                    "example": ""
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.Item"
                    }
                },
                "locale": {
                    "type": "string",
                    "example": "en"
                },
                "oof_shard": {
                    "type": "string",
                    "example": "1"
                },
                "order_uid": {
                    "type": "string",
                    "example": "b563feb7b2b84b6test"
                },
                "payment": {
                    "$ref": "#/definitions/domain.Payment"
                },
                "shardkey": {
                    "type": "string",
                    "example": "9"
                },
                "sm_id": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 99
                },
                "track_number": {
                    "type": "string",
                    "example": "WBILMTESTTRACK"
                }
            }
        },
        "domain.Payment": {
            "type": "object",
            "required": [
                "amount",
                "bank",
                "currency",
                "delivery_cost",
                "goods_total",
                "payment_dt",
                "provider",
                "transaction"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 1817
                },
                "bank": {
                    "type": "string",
                    "example": "alpha"
                },
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "custom_fee": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 0
                },
                "delivery_cost": {
                    "type": "number",
                    "example": 1500
                },
                "goods_total": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 317
                },
                "payment_dt": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 1637907727
                },
                "provider": {
                    "type": "string",
                    "example": "wbpay"
                },
                "request_id": {
                    "type": "string",
                    "example": ""
                },
                "transaction": {
                    "type": "string",
                    "example": "b563feb7b2b84b6test"
                }
            }
        },
        "response.ErrorResponse": {
            "description": "Error response structure",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "WB L0 API",
	Description:      "Test task. Demo service with Kafka, PostgreSQL, cache",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
