basePath: /
definitions:
  domain.Delivery:
    properties:
      address:
        example: Ploshad Mira 15
        type: string
      city:
        example: Kiryat Mozkin
        type: string
      email:
        example: test@gmail.com
        type: string
      name:
        example: Test Testov
        type: string
      phone:
        example: "+9720000000"
        type: string
      region:
        example: Kraiot
        type: string
      zip:
        example: "2639809"
        type: string
    required:
    - address
    - city
    - email
    - name
    - phone
    - region
    - zip
    type: object
  domain.Item:
    properties:
      brand:
        example: Vivienne Sabo
        type: string
      chrt_id:
        example: 9934930
        minimum: 0
        type: integer
      name:
        example: Mascaras
        type: string
      nm_id:
        example: 2389212
        minimum: 0
        type: integer
      price:
        example: 453
        type: number
      rid:
        example: ab4219087a764ae0btest
        type: string
      sale:
        example: 30
        maximum: 100
        minimum: 0
        type: integer
      size:
        example: "0"
        type: string
      status:
        example: 202
        minimum: 0
        type: integer
      total_price:
        example: 317
        type: number
      track_number:
        example: WBILMTESTTRACK
        type: string
    required:
    - brand
    - chrt_id
    - name
    - nm_id
    - price
    - rid
    - size
    - status
    - total_price
    - track_number
    type: object
  domain.Order:
    description: Order information
    properties:
      customer_id:
        example: test
        type: string
      date_created:
        example: "2021-11-26T06:22:19Z"
        type: string
      delivery:
        $ref: '#/definitions/domain.Delivery'
      delivery_service:
        example: meest
        type: string
      entry:
        example: WBIL
        type: string
      internal_signature:
        example: ""
        type: string
      items:
        items:
          $ref: '#/definitions/domain.Item'
        minItems: 1
        type: array
      locale:
        example: en
        type: string
      oof_shard:
        example: "1"
        type: string
      order_uid:
        example: b563feb7b2b84b6test
        type: string
      payment:
        $ref: '#/definitions/domain.Payment'
      shardkey:
        example: "9"
        type: string
      sm_id:
        example: 99
        minimum: 0
        type: integer
      track_number:
        example: WBILMTESTTRACK
        type: string
    required:
    - customer_id
    - date_created
    - delivery
    - delivery_service
    - entry
    - items
    - locale
    - oof_shard
    - order_uid
    - payment
    - shardkey
    - sm_id
    - track_number
    type: object
  domain.Payment:
    properties:
      amount:
        example: 1817
        type: number
      bank:
        example: alpha
        type: string
      currency:
        example: USD
        type: string
      custom_fee:
        example: 0
        minimum: 0
        type: integer
      delivery_cost:
        example: 1500
        type: number
      goods_total:
        example: 317
        minimum: 0
        type: integer
      payment_dt:
        example: 1637907727
        minimum: 0
        type: integer
      provider:
        example: wbpay
        type: string
      request_id:
        example: ""
        type: string
      transaction:
        example: b563feb7b2b84b6test
        type: string
    required:
    - amount
    - bank
    - currency
    - delivery_cost
    - goods_total
    - payment_dt
    - provider
    - transaction
    type: object
  response.ErrorResponse:
    description: Error response structure
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Test task. Demo service with Kafka, PostgreSQL, cache
  termsOfService: http://swagger.io/terms/
  title: WB L0 API
  version: "1.0"
paths:
  /order/{order_uid}:
    get:
      consumes:
      - application/json
      description: Get order details by order UID
      parameters:
      - description: Order UID
        in: path
        name: order_uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Order details
          schema:
            $ref: '#/definitions/domain.Order'
        "400":
          description: Invalid order UID
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Order not found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get order by UID
      tags:
      - orders
swagger: "2.0"
